export const state = {
    currentUser: null,
    username: null,
    loginCode: null,
    currentLanguage: 'en',
    items: [],
    suppliers: [],
    branches: [],
    sections: [],
    transactions: [],
    payments: [],
    purchaseOrders: [],
    purchaseOrderItems: [],
    itemRequests: [],
    activityLog: [],
    currentReceiveList: [],
    currentTransferList: [],
    currentIssueList: [],
    currentPOList: [],
    currentReturnList: [],
    currentRequestList: [],
    currentEditingPOList: [],
    currentAdjustmentList: [],
    modalSelections: new Set(),
    invoiceModalSelections: new Set(),
    allUsers: [],
    allRoles: [],
    backups: [],
    adminContextPromise: {},
    reportSelectedBranches: new Set(),
    reportSelectedSections: new Set(),
    reportSelectedItems: new Set(),
    currentSelectionModal: {
        type: null,
        tempSelections: new Set()
    },
};

export let modalContext = { value: null };